# Generated by Django 4.2.6 on 2023-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_ordermodel_is_shipped"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurantmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="menu_images")),
                ("address", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
