# Generated by Django 4.2.6 on 2023-12-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_restaurantmodel_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurantmodel", old_name="name", new_name="restaurant_name",
        ),
    ]
