# Generated by Django 4.2.6 on 2023-12-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_rename_name_restaurantmodel_restaurant_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurantmodel", old_name="restaurant_name", new_name="name",
        ),
    ]
