# Generated by Django 4.2.6 on 2023-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_rename_restaurant_name_restaurantmodel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurantmodel", old_name="name", new_name="restaurant_name",
        ),
    ]
