# Generated by Django 4.2.6 on 2023-12-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_rename_name_restaurantmodel_restaurant_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="menu_images/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="item", to="customer.restaurantcategory"
                    ),
                ),
            ],
        ),
    ]
