# Generated by Django 4.2.6 on 2023-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_dish_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="restaurant",
            field=models.ManyToManyField(
                related_name="restaurants", to="customer.restaurantmodel"
            ),
        ),
    ]
