# Generated by Django 4.2.6 on 2023-12-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0017_restaurantitems_city_restaurantitems_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Dish",),
    ]
